name: Plugin Bug Report 🪳
description: Report a bug in one of the plugins
title: "[BUG] - "
labels: ["bug"]
body:
  - type: dropdown
    id: plugin_name
    attributes:
      label: Plugin Name
      description: The name of the plugin where the bug occurred.
      options:
        - "Select a plugin"
        - "AutoSwitchStatus"
        - "BetterTTS"
        - "BiggerStreamPreview"
        - "BypassBlockedOrIgnored"
        - "CompleteDiscordQuest"
        - "NoSpotifyPause"
        - "NotifyWhenMuted"
        - "PushToMute"
        - "ShortcutScreenshareScreen"
        - "ShowPing"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: "Describe the bug in detail"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem. You can provide error logs from DevTools Console (Ctrl+Shift+I) as well.
      placeholder: "Add screenshots"
    validations:
      required: false
  - type: input
    id: discord_version
    attributes:
      label: Discord Version
      description: The version of Discord you are using. You can find this by scrolling discord settings categories to the bottom and looking for the version number(Host 1.0.x).
      placeholder: "Enter your Discord version"
    validations:
      required: false
  - type: input
    id: betterdiscord_version
    attributes:
      label: BetterDiscord Version
      description: The version of BetterDiscord you are using. You can find this by scrolling discord settings categories to the bottom and looking for the version number(Betterdiscord 1.x.x).
      placeholder: "Enter your BetterDiscord version"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: The operating system you are using.
      options:
        - "Windows"
        - "macOS"
        - "Linux"
    validations:
      required: false
